# Copyright (c) 2020 Geoffrey Huntley <ghuntley@ghuntley.com>. All rights reserved.
# SPDX-License-Identifier: Proprietary

version: 2
updates:
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: daily
    time: '08:00'
    timezone: Australia/Brisbane
  open-pull-requests-limit: 10

