# Copyright (c) 2020 Geoffrey Huntley <ghuntley@ghuntley.com>. All rights reserved.
# SPDX-License-Identifier: Proprietary

image:
  file: Dockerfile
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod
    
 vscode:
  extensions:
    - Equinusocio.vsc-material-theme@30.0.0:PskT49UZHjppd3FhLdFvtg==
    - christian-kohler.path-intellisense@1.4.2:QnOrf5fk6KiVaQs4cNEP+w==
    - EditorConfig.EditorConfig@0.14.2:S/ZbMLPHoCTxcLLtxqhudQ==
    - fabiospampinato.vscode-todo-plus@4.14.1:hjSbC+uTRZjmH1OzW7TrBw==
    - formulahendry.auto-rename-tag@0.1.1:lKCmLIZAiCM0M8AjDnwCLQ==
    - pnp.polacode@0.3.4:QU0wgEfouOWaz4dz6bLCyg==
    - nopjmp.fairyfloss@0.0.6:8z6NV2TZAuA4cQNvZ/I+Cw==
    - PKief.material-icon-theme@3.9.1:g1O+jL+iaYZp5mMmzpPEug==
    - qezhu.gitlink@0.5.1:CUJojkwlqgxlz1mkuQ/Dfg==
    - jebbs.plantuml@2.13.3:+4zH+3+lcRfRKXGBnGx3Wg==
    - redhat.vscode-yaml@0.6.0:q4JPLkzVuBtCZ1NuiXP2Wg==
    - bbenoist.Nix@1.0.1:TbrU16w37jLfkqA6h20vuQ==
    - aaron-bond.better-comments@2.0.5:YKNfOclR4e8XAxlj4xp2AA==
    - alanz.vscode-hie-server@0.0.30:GhLCt8RZRxMNRFs/qntecA==

