# Copyright (c) 2020 Geoffrey Huntley <ghuntley@ghuntley.com>. All rights reserved.
# SPDX-License-Identifier: Proprietary

name: geoffreyhuntley.com
runtime: dotnet
description: geoffreyhuntley.com

