# Copyright (c) 2020 Geoffrey Huntley <ghuntley@ghuntley.com>. All rights reserved.
# SPDX-License-Identifier: Proprietary

config:
  cloudflare:apiKey:
    secure: AAABAJezQ80Grmkkl5nIZLDo+xzkLrFBdpywBXCqBrWLnD+f45+Xzkx5P4aTn+eFzAMPg5LU/MTTyHeCpByFUiaNO+eg
  cloudflare:email: ghuntley@ghuntley.com

