# Copyright (c) 2020 Geoffrey Huntley <ghuntley@ghuntley.com>. All rights reserved.
# SPDX-License-Identifier: Proprietary

config:
  cloudflare:apiKey:
    secure: AAABAHBtVoJ8KpXSWr8BVCo+7f5j5u2Jrz0rzIeYEA/d1npkW7V5FS0uIHStQf4LyXGghHANFi91GC9E3o1d4UMUHti+

